# Generated by Django 2.2.1 on 2019-06-20 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateField()),
                ('description', models.CharField(max_length=250)),
                ('is_price_fixed', models.BooleanField()),
                ('max_price', models.FloatField()),
                ('fixed_price', models.FloatField()),
                ('min_price', models.FloatField()),
                ('title', models.CharField(max_length=100)),
                ('attachment_id', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=250)),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campaign.Campaign')),
            ],
        ),
    ]
