# Generated by Django 2.2.1 on 2019-06-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('address', models.CharField(max_length=200, unique=True)),
                ('tier', models.PositiveIntegerField()),
                ('icon_id', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
