# Generated by Django 2.2.1 on 2019-06-20 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Campaign_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_id', models.CharField(max_length=100)),
                ('meta_data', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('agency_status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=10)),
                ('is_draft', models.BooleanField()),
                ('media_url', models.URLField()),
                ('reject_reason', models.CharField(max_length=200)),
                ('brand_status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=10)),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campaign_content.Campaign_content')),
            ],
        ),
    ]
