# Generated by Django 2.2.1 on 2019-06-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('tax', models.FloatField()),
                ('raised_at', models.DateTimeField()),
                ('cleared_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Cleared', 'Cleared'), ('Rejected', 'Rejected'), ('Deleted', 'Deleted')], max_length=10)),
                ('rejected_by', models.CharField(max_length=30)),
                ('rejection_reason', models.CharField(max_length=100)),
            ],
        ),
    ]
