# Generated by Django 2.2.1 on 2019-06-20 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media_handles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=50, unique=True)),
                ('meta_data', models.CharField(max_length=200)),
                ('params', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=100, unique=True)),
                ('reset_token', models.CharField(max_length=100)),
                ('token_expiry_date', models.DateField()),
                ('platform_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Platform.Platform')),
            ],
        ),
    ]
