# Generated by Django 2.2.1 on 2019-06-20 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('campaign_description_id', models.PositiveIntegerField()),
                ('approved_by', models.CharField(max_length=30)),
                ('agency_notes', models.CharField(max_length=100)),
                ('deleted_at', models.DateTimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pinned', models.BooleanField()),
                ('moderation_url_sharing', models.URLField()),
                ('price', models.FloatField()),
                ('total_slots', models.PositiveIntegerField()),
                ('what_you_get', models.CharField(max_length=30)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Brand.Brand')),
            ],
        ),
    ]
