# Generated by Django 2.2.1 on 2019-06-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reevaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reevaluated_at', models.DateTimeField()),
                ('reevaluated_by', models.CharField(max_length=50)),
            ],
        ),
    ]
